name: analyze & test cat example

env:
  FLUTTER_VERSION: stable

on:
  pull_request:
  push:

jobs:
  analyze:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      
      - name: "Analyze"
        run: cd examples/fun_cat_responses && flutter pub get && flutter analyze .

      - name: "Format"
        run: cd examples/fun_cat_responses && flutter format lib/** --set-exit-if-changed

      - name: "Run tests"
        run: cd examples/fun_cat_responses && flutter test -r expanded